USE STAGING;

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP TABLE IF EXISTS [dbo].[JSONLogs]; 
GO 
CREATE TABLE [dbo].[JSONLogs](
	[_id] [bigint] IDENTITY(1,1) NOT NULL,
	[JSONDOCUMENT] [nvarchar](max) NULL,
	[FILENAME] [varchar](150) NULL,
	[IMPORTDATE] [datetime] NULL,
	[cs_jsonDocumentCheckSum]  AS (checksum([JSONDOCUMENT]))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[JSONLogs] ADD PRIMARY KEY CLUSTERED 
(
	[_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JSONLogs]  WITH CHECK ADD  CONSTRAINT [JSONDOCUMENT record should be formatted as JSON] CHECK  ((isjson([JSONDOCUMENT])=(1)))
GO
ALTER TABLE [dbo].[JSONLogs] CHECK CONSTRAINT [JSONDOCUMENT record should be formatted as JSON]
GO
ALTER TABLE [dbo].[JSONLogs] ADD  CONSTRAINT [DF_jsonlogs_created_dt]  DEFAULT (getdate()) FOR [IMPORTDATE]
GO
